[meta]
name = "DXBallGame"
language = "cpp"
description = "A clone of the games 'DX' and 'Breakout'"

[git]
repo = "https://github.com/thoth-tech/DXBallGame.git"

[emulationstation]
image = "images/title.png"
genre = "Breakout clone"
developer = "Thoth Tech"
rating = 1.0
