on: [push]

jobs:
  build_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["rpi", "linux"]
    steps:
      - name: Update apt repo
        run: sudo apt update

      - name: Install splashkit
        run: |
          curl -s https://raw.githubusercontent.com/splashkit/skm/master/install-scripts/skm-install.sh | bash
          ~/.splashkit/skm linux install
          ~/.splashkit/skm global install

      - name: Install dependencies
        run: sudo apt-get install -y dotnet-host g++-arm-linux-gnueabihf

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Clone flipper repo
        uses: actions/checkout@v4

      - name: Run flipper
        run: |
          mkdir -p build
          cd build
          python ../flipper.py --path .. ${{ matrix.arch == 'rpi' && '--cs-runtime linux-arm --cpp-prefix arm-linux-gnueabihf-' || '' }}
